"use client";

import { motion, AnimatePresence } from "framer-motion";
import {
  Home,
  Search,
  Library,
  Plus,
  ArrowRight,
  List,
  ChevronLeft,
  ChevronRight,
  Bell,
  Users,
  Play,
  Pause,
  Check,
  Settings,
  Heart,
  Mic2,
  Radio,
  Coffee,
  Moon,
  Zap,
  Smile,
  MoreHorizontal,
  Flame,
  Shuffle,
  MessageSquare,
  Compass,
  Share2,
  Send,
  Volume2,
  Image as ImageIcon,
  Music as MusicIcon,
  BarChart2,
} from "lucide-react";
import { useMemo, useState, useEffect, useCallback } from "react";
import { useQuery } from "@tanstack/react-query";
import { PlayerShell } from "@/features/player/player-shell";
import { usePlayerStore } from "@/store/player-store";
import { TrackArt } from "@/components/track-art";
import { SearchPanelV2 } from "@/features/search/search-panel-v2";
import { SettingsPanelV2 } from "@/features/settings/settings-panel-v2";
import type { Track } from "@/types/music";

type AppView = "home" | "search" | "settings" | "library" | "hotlist" | "community";

// ─── Mood definitions ──────────────────────────────────────────────────────────

const MOODS = [
  { id: "happy",     label: "Happy",     icon: Smile,  color: "#f9a825", query: "happy upbeat songs" },
  { id: "calm",      label: "Chill",     icon: Coffee, color: "#29b6f6", query: "chill lofi relax" },
  { id: "energetic", label: "Energetic", icon: Zap,    color: "#ef5350", query: "workout gym motivation" },
  { id: "focus",     label: "Focus",     icon: Mic2,   color: "#66bb6a", query: "study focus instrumental" },
  { id: "romantic",  label: "Romantic",  icon: Heart,  color: "#ec407a", query: "romantic love bollywood" },
  { id: "sleep",     label: "Sleep",     icon: Moon,   color: "#7e57c2", query: "sleep calm meditation" },
  { id: "party",     label: "Party",     icon: Zap,    color: "#ff7043", query: "party edm dance" },
  { id: "travel",    label: "Travel",    icon: Radio,  color: "#26a69a", query: "road trip travel songs" },
];

// ─── Dynamic color extraction (simple dominant color from cover hue) ───────────
function hashColorFromString(str: string): string {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  const hue = Math.abs(hash) % 360;
  return `hsl(${hue}, 55%, 25%)`;
}

// ─── Component ─────────────────────────────────────────────────────────────────

export function MusicHome() {
  const {
    playTrack,
    setQueue,
    recentlyPlayed,
    likedIds,
    currentTrack,
    isPlaying,
    togglePlaying,
  } = usePlayerStore();

  const [appView, setAppView] = useState<AppView>("home");
  const [selectedPlaylist, setSelectedPlaylist] = useState<typeof playlistList[number] | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [activeTab, setActiveTab] = useState<"music" | "mood">("music");
  const [activeMood, setActiveMood] = useState<string | null>(null);
  const [dynamicBg, setDynamicBg] = useState("hsl(210, 30%, 8%)");
  const [trackComments, setTrackComments] = useState<Record<string, { id: string; author: string; text: string; time: string; avatarUrl?: string }[]>>({});
  const [newCommentText, setNewCommentText] = useState("");

  const HERO_SLIDES = useMemo(() => [
    {
      id: "chill",
      tagline: "☕ GOOD EVENING",
      title: "Chill, Relax and just ",
      highlightWord: "breathe.",
      desc: "The perfect lofi to ease your mind and connect with amazing people.",
      bg: "/lofiera_hero_banner.png",
      playlistId: "study",
    },
    {
      id: "ai-radio",
      tagline: "✨ AI SMART RADIO",
      title: "AI Recommended Lofi ",
      highlightWord: "Generator.",
      desc: "Listen to high-fidelity tracks dynamically selected and generated by our recommendation engine.",
      bg: "/covers/sleepless-nights.png",
      playlistId: "rainy",
    },
    {
      id: "public-playlist",
      tagline: "👥 COMMUNITY SPOTLIGHT",
      title: "Top Voted Public ",
      highlightWord: "Playlist.",
      desc: "Explore public playlists created by the community and voted by lofi listeners.",
      bg: "/covers/coffee-lofi.png",
      playlistId: "coffee",
    }
  ], []);

  const [currentHeroSlide, setCurrentHeroSlide] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentHeroSlide((prev) => (prev + 1) % HERO_SLIDES.length);
    }, 7000);
    return () => clearInterval(timer);
  }, [HERO_SLIDES.length]);

  // Debounce search
  useEffect(() => {
    const timer = setTimeout(() => setDebouncedSearch(searchQuery.trim()), 300);
    return () => clearTimeout(timer);
  }, [searchQuery]);

  // Dynamic background color from current track
  useEffect(() => {
    if (currentTrack) {
      const color = hashColorFromString(currentTrack.title + currentTrack.artist);
      setDynamicBg(color);
    }
  }, [currentTrack]);

  // ─── Data fetching ─────────────────────────────────────────────────────────

  const trendingQuery = useQuery({
    queryKey: ["trending"],
    queryFn: async () => {
      const res = await fetch("/api/search?q=Trending%20Hindi%20Songs%202026&limit=20");
      if (!res.ok) throw new Error("Failed to fetch");
      const data = await res.json();
      return data.tracks as Track[];
    },
  });

  const globalHitsQuery = useQuery({
    queryKey: ["globalHits"],
    queryFn: async () => {
      const res = await fetch("/api/search?q=Trending%20Global%20Hits%202026&limit=20");
      if (!res.ok) throw new Error("Failed to fetch");
      const data = await res.json();
      return data.tracks as Track[];
    },
  });

  const newReleasesQuery = useQuery({
    queryKey: ["newReleases"],
    queryFn: async () => {
      const res = await fetch("/api/search?q=latest%20released%20songs%202026&limit=20");
      if (!res.ok) throw new Error("Failed to fetch");
      const data = await res.json();
      return data.tracks as Track[];
    },
  });

  const searchQueryResult = useQuery({
    queryKey: ["search", debouncedSearch],
    queryFn: async () => {
      const res = await fetch(`/api/search?q=${encodeURIComponent(debouncedSearch)}&limit=20`);
      if (!res.ok) throw new Error("Search failed");
      const data = await res.json();
      return data.tracks as Track[];
    },
    enabled: debouncedSearch.length > 0,
  });

  const moodQuery = useQuery({
    queryKey: ["mood", activeMood],
    queryFn: async () => {
      if (!activeMood) return [];
      const mood = MOODS.find((m) => m.id === activeMood)!;
      const res = await fetch(`/api/search?q=${encodeURIComponent(mood.query)}&limit=20`);
      if (!res.ok) throw new Error("Mood fetch failed");
      const data = await res.json();
      return data.tracks as Track[];
    },
    enabled: !!activeMood,
  });

  const BACKUP_COVERS = useMemo(() => [
    "/covers/late-night-study.png",
    "/covers/rainy-day-lofi.png",
    "/covers/sunset-drive.png",
    "/covers/sleepless-nights.png",
    "/covers/coffee-lofi.png",
  ], []);

  const deduplicateCovers = useCallback((tracksList: Track[]): Track[] => {
    const seenCovers = new Set<string>();
    return tracksList.map((track, index) => {
      const isGeneric = !track.cover || track.cover.includes("midnight-arcade.svg");
      if (isGeneric || seenCovers.has(track.cover)) {
        const backupCover = BACKUP_COVERS[index % BACKUP_COVERS.length];
        return { ...track, cover: backupCover };
      }
      seenCovers.add(track.cover);
      return track;
    });
  }, [BACKUP_COVERS]);

  const tracks = useMemo(() => deduplicateCovers(trendingQuery.data || []), [trendingQuery.data, deduplicateCovers]);
  const globalHits = useMemo(() => deduplicateCovers(globalHitsQuery.data || []), [globalHitsQuery.data, deduplicateCovers]);
  const newReleases = useMemo(() => deduplicateCovers(newReleasesQuery.data || []), [newReleasesQuery.data, deduplicateCovers]);
  const searchTracks = searchQueryResult.data || [];
  const moodTracks = moodQuery.data || [];

  const likedTracks = useMemo(
    () => tracks.filter((t) => likedIds.includes(t.id)),
    [likedIds, tracks]
  );

  const playlistList = useMemo(() => [
    {
      id: "favs",
      name: "Liked Songs",
      desc: `Playlist • ${likedIds.length} songs`,
      tracks: likedTracks,
      cover: likedTracks[0]?.cover || "/covers/late-night-study.png",
      gradient: "from-[#ff7a8a] to-[#090a10]",
    },
    {
      id: "study",
      name: "Late Night Study",
      desc: "Focus • Relax • Repeat",
      tracks: tracks.slice(0, 10),
      cover: "/covers/late-night-study.png",
      gradient: "from-[#ff7a8a] to-[#090a10]",
    },
    {
      id: "rainy",
      name: "Rainy Day LoFi",
      desc: "Rain • Window • LoFi",
      tracks: tracks.slice(5, 12),
      cover: "/covers/rainy-day-lofi.png",
      gradient: "from-[#3b82f6] to-[#090a10]",
    },
    {
      id: "drive",
      name: "Sunset Drive",
      desc: "Chill • Drive • Unwind",
      tracks: tracks.slice(10, 17),
      cover: "/covers/sunset-drive.png",
      gradient: "from-[#f59e0b] to-[#090a10]",
    },
    {
      id: "sleepless",
      name: "Sleepless Nights",
      desc: "Dark • Calm • LoFi",
      tracks: tracks.slice(2, 9),
      cover: "/covers/sleepless-nights.png",
      gradient: "from-[#8b5cf6] to-[#090a10]",
    },
    {
      id: "coffee",
      name: "Coffee & LoFi",
      desc: "Coffee • Chill • Vibes",
      tracks: tracks.slice(7, 14),
      cover: "/covers/coffee-lofi.png",
      gradient: "from-[#ff7a8a] to-[#090a10]",
    },
  ], [likedIds.length, likedTracks, tracks]);

  function play(track: Track, queueList: Track[] = []) {
    const q = queueList.length > 0 ? queueList : tracks;
    setQueue(q);
    playTrack(track, q);
  }

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-[#090a10] font-sans text-white select-none">
      <div className="flex flex-1 overflow-hidden p-3 gap-3">

        {/* ── Left Sidebar ──────────────────────────────────────────────── */}
        <aside className="hidden md:flex w-[260px] shrink-0 flex-col gap-3 overflow-hidden h-[calc(100vh-110px)]">
          
          {/* Logo Card */}
          <div className="rounded-2xl bg-[#141724] border border-white/[0.04] p-5 flex flex-col flex-1">
            <div className="flex items-center gap-2 mb-6">
              <div className="h-9 w-9 rounded-xl bg-gradient-to-tr from-[#ff7a8a] to-[#ff9aa6] flex items-center justify-center shadow-lg shadow-[#ff7a8a]/20">
                <span className="text-black font-black text-lg">L</span>
              </div>
              <div className="flex flex-col">
                <span className="text-white font-black text-lg tracking-tight leading-none">LoFiera</span>
                <span className="text-[9px] text-[#ff7a8a] font-bold tracking-wider uppercase mt-0.5">Feel • Connect • Chill</span>
              </div>
            </div>

            {/* Profile widget */}
            <div className="flex items-center gap-3 p-3 rounded-2xl bg-white/[0.02] border border-white/[0.04] mb-4 relative group">
              <div className="h-10 w-10 rounded-full bg-gradient-to-tr from-[#ff7a8a] to-purple-500 relative overflow-hidden shrink-0 border border-white/10">
                <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url('/covers/late-night-study.png')` }} />
                <div className="absolute bottom-0 right-0 h-2.5 w-2.5 rounded-full bg-emerald-500 border-2 border-[#141724]" />
              </div>
              <div className="min-w-0 flex-1">
                <p className="truncate text-xs font-bold text-white">rishavraj</p>
                <p className="truncate text-[9px] text-[#8b8e9f] font-semibold mt-0.5">Lofi Enthusiast</p>
              </div>
              <button className="text-[#8b8e9f] hover:text-white transition"><MoreHorizontal size={16} /></button>
            </div>

            {/* Navigation links */}
            <div className="flex flex-col gap-1.5">
              {[
                { view: "home", label: "Home", icon: Home },
                { view: "search", label: "Explore", icon: Compass },
                { view: "radio", label: "Radio", icon: Radio },
                { view: "library", label: "Library", icon: Library },
                { view: "playlists", label: "Playlists", icon: List },
                { view: "liked", label: "Liked Songs", icon: Heart },
                { view: "community", label: "Community", icon: Users },
              ].map((item) => {
                const Icon = item.icon;
                const isActive = appView === item.view || (item.view === "library" && appView === "library" && !selectedPlaylist);
                
                return (
                  <button
                    key={item.label}
                    onClick={() => {
                      if (item.view === "liked") {
                        const favs = playlistList.find(p => p.id === "favs");
                        if (favs) setSelectedPlaylist(favs);
                        setAppView("library");
                      } else if (item.view === "playlists") {
                        setSelectedPlaylist(null);
                        setAppView("library");
                      } else {
                        setSelectedPlaylist(null);
                        setAppView(item.view as any);
                      }
                    }}
                    className={`flex items-center gap-4 py-2.5 px-4 rounded-xl text-sm font-semibold transition ${
                      isActive 
                        ? "bg-[#ff7a8a]/10 text-[#ff7a8a] border border-[#ff7a8a]/20 font-bold" 
                        : "text-[#8b8e9f] hover:text-white hover:bg-white/[0.02]"
                    }`}
                  >
                    <Icon size={18} className={isActive ? "text-[#ff7a8a]" : "text-[#8b8e9f]"} />
                    <span>{item.label}</span>
                  </button>
                );
              })}
            </div>

            {/* Spacer */}
            <div className="flex-1" />

            {/* Premium Card to fill space */}
            <div className="mt-6 p-4 rounded-2xl bg-gradient-to-br from-[#ff7a8a]/10 to-purple-500/5 border border-white/[0.05] flex flex-col gap-3 relative overflow-hidden group">
              <div className="absolute top-[-50px] right-[-50px] w-24 h-24 bg-[#ff7a8a]/10 rounded-full blur-xl group-hover:scale-150 transition-all duration-700 pointer-events-none" />
              <h5 className="font-black text-xs text-white tracking-wide">LoFiera Premium</h5>
              <p className="text-[10px] text-white/50 leading-relaxed font-medium">Unlock high-fidelity audio, smart playlists and ad-free streaming.</p>
              <button className="w-full py-2 rounded-xl bg-[#ff7a8a] text-black font-black text-[10px] hover:bg-[#ff9aa6] transition tracking-wider uppercase">Upgrade Now</button>
            </div>
          </div>
        </aside>

        {/* ── Middle Content Wrapper ──────────────────────────────────────── */}
        <div className="flex-1 flex flex-col gap-3 overflow-hidden h-full">
          <main className="flex-1 rounded-2xl overflow-y-auto flex flex-col relative transition-all duration-700 bg-[#0d0f1a] border border-white/[0.04]">
          {/* Header search bar */}
          <header className="sticky top-0 bg-[#0d0f1a]/85 backdrop-blur-md z-20 px-6 py-4 flex items-center justify-between gap-4 border-b border-white/[0.03]">
            {appView === "home" && !selectedPlaylist ? (
              <div className="md:hidden flex items-center gap-3">
                <div className="h-9 w-9 rounded-full bg-gradient-to-tr from-[#ff7a8a] to-purple-500 relative overflow-hidden shrink-0 border border-white/10">
                  <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url('/covers/late-night-study.png')` }} />
                </div>
                <div className="flex flex-col">
                  <span className="text-white font-black text-sm tracking-tight leading-none">LoFiera</span>
                  <span className="text-[8px] text-[#ff7a8a] font-bold tracking-wider uppercase mt-0.5">Feel • Connect • Chill</span>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-2 min-h-[32px]">
                {(selectedPlaylist || appView !== "home") && (
                  <button
                    onClick={() => {
                      setSelectedPlaylist(null);
                      setAppView("home");
                    }}
                    className="h-8 w-8 rounded-full bg-black/20 border border-white/[0.05] flex items-center justify-center text-gray-400 hover:text-white transition"
                  >
                    <ChevronLeft size={16} />
                  </button>
                )}
              </div>
            )}
            
            <div className="flex items-center gap-3">
              <button className="h-9 w-9 rounded-xl bg-white/[0.03] border border-white/[0.05] flex items-center justify-center hover:scale-105 transition text-gray-300 hover:text-[#ff7a8a]">
                <Bell size={16} />
              </button>
              <div className="h-9 w-9 rounded-xl bg-[#ff7a8a] text-black cursor-pointer hover:scale-105 transition flex items-center justify-center text-xs font-black shadow-lg shadow-[#ff7a8a]/10">
                R
              </div>
            </div>
          </header>

          {/* Body */}
          <div className="px-6 py-6 pb-40 flex flex-col gap-7">

            {/* View-specific content */}
            {appView === "search" ? (
              <SearchPanelV2 onPlay={(track, queue) => play(track, queue || tracks)} />
            ) : appView === "settings" ? (
              <SettingsPanelV2 />
            ) : appView === "library" && selectedPlaylist ? (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex flex-col gap-6"
                >
                  <div className="flex items-center gap-3 text-sm">
                    <button
                      onClick={() => setSelectedPlaylist(null)}
                      className="h-10 w-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/5 transition flex items-center justify-center text-white"
                    >
                      <ChevronLeft size={20} />
                    </button>
                    <span className="font-bold text-white/50">Back to Library</span>
                  </div>

                  <div className="relative flex flex-col md:flex-row gap-6 md:gap-8 items-center md:items-end p-6 md:p-8 rounded-[32px] overflow-hidden border border-white/[0.06] bg-gradient-to-b from-white/[0.04] to-transparent shadow-xl">
                    <div className={`absolute top-[-50%] left-[-20%] w-[120%] h-[200%] bg-gradient-to-br ${selectedPlaylist.gradient || "from-neutral-800 to-transparent"} opacity-20 filter blur-[80px] pointer-events-none`} />

                    <div className="w-48 h-48 sm:w-52 sm:h-52 rounded-[32px] overflow-hidden shadow-[0_25px_50px_-12px_rgba(0,0,0,0.8)] bg-[#282828] relative shrink-0 border border-white/10 group">
                      <TrackArt src={selectedPlaylist.cover} alt={selectedPlaylist.name} size={208} className="transition-transform duration-700 group-hover:scale-105" />
                    </div>

                    <div className="flex flex-col gap-2 min-w-0 text-center md:text-left z-10">
                      <span className="text-[10px] text-[#ff7a8a] uppercase tracking-[0.2em] font-extrabold">
                        {selectedPlaylist.id === "favs" ? "Private Collection" : "Curated Playlist"}
                      </span>
                      <h2 className="text-4xl md:text-5xl font-black text-white truncate drop-shadow-md tracking-tight leading-none">
                        {selectedPlaylist.name}
                      </h2>
                      <p className="text-sm text-white/70 font-medium max-w-xl leading-relaxed">
                        {selectedPlaylist.desc}
                      </p>
                      
                      <div className="flex items-center justify-center md:justify-start gap-2 text-xs text-white/45 mt-1 font-semibold">
                        <span className="text-white/80">LoFiera</span>
                        <span>•</span>
                        <span>{selectedPlaylist.tracks.length} tracks</span>
                        <span>•</span>
                        <span>
                          {Math.round(
                            selectedPlaylist.tracks.reduce((acc: number, t: Track) => acc + (t.duration || 0), 0) / 60
                          )}{" "}
                          min
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between gap-4 px-2 py-1">
                    <div className="flex items-center gap-4">
                      <button
                        onClick={() => selectedPlaylist.tracks.length > 0 && play(selectedPlaylist.tracks[0], selectedPlaylist.tracks)}
                        disabled={selectedPlaylist.tracks.length === 0}
                        className="h-14 w-14 rounded-full bg-[#ff7a8a] text-black font-bold flex items-center justify-center hover:scale-105 active:scale-95 hover:bg-[#ff9aa6] transition duration-300 shadow-[0_4px_20px_rgba(255,122,138,0.3)] disabled:opacity-50"
                      >
                        <Play size={24} className="fill-black text-black ml-1" />
                      </button>

                      <button
                        onClick={() => {
                          if (selectedPlaylist.tracks.length > 0) {
                            const { toggleShuffle } = usePlayerStore.getState();
                            toggleShuffle();
                            play(selectedPlaylist.tracks[Math.floor(Math.random() * selectedPlaylist.tracks.length)], selectedPlaylist.tracks);
                          }
                        }}
                        disabled={selectedPlaylist.tracks.length === 0}
                        className="h-11 px-6 rounded-full bg-white/5 hover:bg-white/10 text-white border border-white/10 font-bold flex items-center justify-center gap-2 hover:scale-[1.02] active:scale-[0.98] transition backdrop-blur-md disabled:opacity-50"
                      >
                        <Shuffle size={16} />
                        <span className="text-xs">Shuffle</span>
                      </button>
                    </div>

                    <div className="flex items-center gap-3">
                      <button className="h-10 w-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/5 transition flex items-center justify-center text-white/70 hover:text-white">
                        <MoreHorizontal size={20} />
                      </button>
                    </div>
                  </div>

                  <div className="flex flex-col mt-2">
                    <div className="flex items-center gap-4 px-4 py-2 text-xs font-bold uppercase tracking-wider text-white/45 border-b border-white/5">
                      <div className="w-8 text-center">#</div>
                      <div className="flex-1">Title</div>
                      <div className="w-24 text-right hidden sm:block">Duration</div>
                      <div className="w-10"></div>
                    </div>

                    <div className="flex flex-col gap-1 mt-2">
                        {selectedPlaylist.tracks.map((track: Track, i: number) => {
                          const isCurrent = currentTrack?.id === track.id;
                          return (
                            <div
                              key={track.id}
                              onClick={() => play(track, selectedPlaylist.tracks)}
                              className={`flex items-center gap-4 py-3 px-4 rounded-[16px] cursor-pointer hover:bg-white/5 group transition ${
                                isCurrent ? "bg-white/[0.04] border border-white/5" : "border border-transparent"
                              }`}
                            >
                              <div className="w-8 text-center text-xs font-semibold text-white/45">
                                {isCurrent && isPlaying ? (
                                  <div className="flex justify-center items-end gap-0.5 h-3.5 w-full">
                                    <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_100ms]" style={{ height: "60%" }} />
                                    <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_300ms]" style={{ height: "100%" }} />
                                    <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_500ms]" style={{ height: "40%" }} />
                                  </div>
                                ) : (
                                  String(i + 1).padStart(2, "0")
                                )}
                              </div>

                              <div className="h-12 w-12 rounded-xl overflow-hidden shrink-0 bg-[#282828] border border-white/5 shadow-md">
                                <TrackArt src={track.cover} alt={track.title} size={48} />
                              </div>

                              <div className="min-w-0 flex-1">
                                <h4 className={`truncate font-bold text-sm transition ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                                  {track.title}
                                </h4>
                                <p className="truncate text-xs text-white/50 mt-0.5 font-medium">{track.artist}</p>
                              </div>

                              <span className="text-xs text-white/45 font-semibold tabular-nums hidden sm:block shrink-0 w-24 text-right">
                                {formatDuration(track.duration)}
                              </span>

                              <div className="w-10 flex justify-end">
                                <button className="text-white/40 hover:text-white transition p-1.5 rounded-full hover:bg-white/5 opacity-0 group-hover:opacity-100">
                                  <MoreHorizontal size={18} />
                                </button>
                              </div>
                            </div>
                          );
                        })}
                    </div>
                  </div>
                </motion.div>
            ) : appView === "hotlist" ? (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex flex-col gap-6"
              >
                <div className="flex items-center gap-3">
                  <div className="h-12 w-12 rounded-full bg-red-500/10 flex items-center justify-center text-red-500">
                    <Flame size={24} className="fill-current" />
                  </div>
                  <div>
                    <h3 className="font-bold text-2xl">Hotlist</h3>
                    <p className="text-sm text-gray-400">Trending tracks and popular hits updated hourly</p>
                  </div>
                </div>

                <div className="flex flex-col divide-y divide-white/5">
                  {tracks.slice(0, 15).map((track, i) => {
                    const isCurrent = currentTrack?.id === track.id;
                    return (
                      <div
                        key={track.id}
                        onClick={() => play(track, tracks)}
                        className={`flex items-center gap-4 py-3 px-2 rounded-xl cursor-pointer hover:bg-white/5 group transition ${isCurrent ? "bg-white/5" : ""}`}
                      >
                        <div className="w-6 text-center text-xs font-semibold text-gray-500">
                          {isCurrent && isPlaying ? (
                            <div className="flex justify-center items-end gap-0.5 h-3.5 w-full">
                              <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_100ms]" style={{ height: "60%" }} />
                              <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_300ms]" style={{ height: "100%" }} />
                              <div className="w-0.5 bg-[#ff7a8a] animate-[bounce_0.8s_infinite_500ms]" style={{ height: "40%" }} />
                            </div>
                          ) : (
                            String(i + 1).padStart(2, "0")
                          )}
                        </div>
                        <div className="h-11 w-11 rounded-lg overflow-hidden shrink-0 bg-[#282828]">
                          <TrackArt src={track.cover} alt={track.title} size={44} />
                        </div>
                        <div className="min-w-0 flex-1">
                          <h4 className={`truncate font-semibold text-sm transition ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                            {track.title}
                          </h4>
                          <p className="truncate text-xs text-gray-400 mt-0.5">{track.artist} · {track.album}</p>
                        </div>
                        <span className="text-xs text-gray-500 font-medium tabular-nums hidden sm:block shrink-0">
                          {formatDuration(track.duration)}
                        </span>
                        <button className="text-gray-500 hover:text-white transition p-1.5">
                          <MoreHorizontal size={18} />
                        </button>
                      </div>
                    );
                  })}
                </div>
              </motion.div>
            ) : appView === "community" ? (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex flex-col gap-6"
              >
                <div className="flex items-center justify-between border-b border-white/[0.04] pb-3">
                  <h3 className="font-black text-2xl text-white">Community</h3>
                </div>

                {/* Input card */}
                <div className="p-4 rounded-2xl bg-[#141724] border border-white/[0.04] flex flex-col gap-3">
                  <div className="flex items-start gap-2.5">
                    <div className="h-8 w-8 rounded-full bg-[#ff7a8a]/20 border border-[#ff7a8a]/10 relative overflow-hidden shrink-0">
                      <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url('/covers/late-night-study.png')` }} />
                    </div>
                    <textarea 
                      className="bg-transparent text-xs w-full outline-none text-white placeholder-[#8b8e9f] resize-none h-12 py-1"
                      placeholder="Share your thoughts..."
                    />
                  </div>
                  <div className="flex items-center justify-between border-t border-white/[0.04] pt-2.5">
                    <div className="flex items-center gap-3 text-[#8b8e9f]">
                      <button className="hover:text-[#ff7a8a] transition"><ImageIcon size={16} /></button>
                      <button className="hover:text-[#ff7a8a] transition"><MusicIcon size={16} /></button>
                      <button className="hover:text-[#ff7a8a] transition"><BarChart2 size={16} /></button>
                    </div>
                    <button className="px-4 py-1.5 rounded-xl bg-[#ff7a8a] text-black font-black text-xs hover:bg-[#ff9aa6] transition">Post</button>
                  </div>
                </div>

                {/* Posts Feed */}
                <div className="flex flex-col gap-4">
                  {/* Feed post 1 */}
                  <div className="p-4 rounded-2xl bg-[#141724] border border-white/[0.04] flex flex-col gap-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <div className="h-8 w-8 rounded-full bg-indigo-500 overflow-hidden shrink-0 border border-white/10" style={{ backgroundImage: `url('/covers/coffee-lofi.png')`, backgroundSize: "cover" }} />
                        <div>
                          <h5 className="text-xs font-bold text-white leading-tight">SakuraMelody</h5>
                          <span className="text-[9px] text-[#8b8e9f]">2h ago</span>
                        </div>
                      </div>
                      <button className="text-[#8b8e9f] hover:text-white transition">···</button>
                    </div>
                    <p className="text-xs text-white/80 leading-relaxed">
                      This lofi track hits different when it rains 🌧 What's your go-to rain lofi?
                    </p>
                    
                    {/* Embedded Song card */}
                    <div className="flex items-center gap-3.5 p-2 rounded-2xl bg-white/[0.02] border border-white/[0.04] group transition duration-300">
                      <div className="relative h-12 w-12 rounded-xl overflow-hidden shrink-0 bg-[#282828] shadow-md">
                        <TrackArt src="/covers/rainy-day-lofi.png" alt="night rain" size={48} />
                        <div 
                          onClick={() => {
                            const lofi = playlistList.find(p => p.id === "rainy");
                            if (lofi && lofi.tracks.length > 0) play(lofi.tracks[0], lofi.tracks);
                          }}
                          className="absolute inset-0 bg-black/40 flex items-center justify-center cursor-pointer transition hover:bg-black/60"
                        >
                          <Play size={14} className="fill-white text-white ml-0.5" />
                        </div>
                      </div>
                      <div className="min-w-0 flex-1">
                        <h6 className="text-[12px] font-extrabold text-white truncate leading-tight">night rain</h6>
                        <span className="text-[10px] text-white/50 block mt-1 font-medium">by kupla</span>
                      </div>
                      <span className="text-[10px] text-white/40 shrink-0 font-bold pr-2 tabular-nums">2:45</span>
                    </div>

                    <div className="flex items-center gap-4 text-xs text-[#8b8e9f] mt-1 font-semibold">
                      <button className="flex items-center gap-1 hover:text-red-400 transition"><Heart size={14} /> 128</button>
                      <button className="flex items-center gap-1 hover:text-[#ff7a8a] transition"><MessageSquare size={14} /> 32</button>
                    </div>
                  </div>

                  {/* Feed post 2 */}
                  <div className="p-4 rounded-2xl bg-[#141724] border border-white/[0.04] flex flex-col gap-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <div className="h-8 w-8 rounded-full bg-emerald-500 overflow-hidden shrink-0 border border-white/10" style={{ backgroundImage: `url('/covers/late-night-study.png')`, backgroundSize: "cover" }} />
                        <div>
                          <h5 className="text-xs font-bold text-white leading-tight">LofiClouds</h5>
                          <span className="text-[9px] text-[#8b8e9f]">5h ago</span>
                        </div>
                      </div>
                      <button className="text-[#8b8e9f] hover:text-white transition">···</button>
                    </div>
                    <p className="text-xs text-white/80 leading-relaxed">
                      Just finished my exams! LoFi and freedom feels so good right now ☁✨
                    </p>
                    <div className="flex items-center gap-4 text-xs text-[#8b8e9f] mt-1 font-semibold">
                      <button className="flex items-center gap-1 hover:text-red-400 transition"><Heart size={14} /> 96</button>
                      <button className="flex items-center gap-1 hover:text-[#ff7a8a] transition"><MessageSquare size={14} /> 18</button>
                    </div>
                  </div>

                  {/* Who to Follow */}
                  <div className="p-4 rounded-2xl bg-[#141724] border border-white/[0.04] flex flex-col gap-3">
                    <span className="text-[10px] uppercase tracking-wider font-extrabold text-[#ff7a8a]">Who to Follow</span>
                    <div className="flex flex-col gap-3">
                      {[
                        { name: "ChillVibes", handle: "@chillvibes", avatar: "/covers/sunset-drive.png", followers: "1.2K followers" },
                        { name: "LofiGirl", handle: "@lofigirl", avatar: "/covers/late-night-study.png", followers: "3.4K followers" },
                        { name: "NightOwl", handle: "@nightowl", avatar: "/covers/sleepless-nights.png", followers: "2.1K followers" },
                      ].map((user) => (
                        <div key={user.handle} className="flex items-center justify-between">
                          <div className="flex items-center gap-2.5 min-w-0">
                            <div className="h-8 w-8 rounded-full bg-[#ff7a8a]/20 overflow-hidden shrink-0 border border-white/10" style={{ backgroundImage: `url(${user.avatar})`, backgroundSize: "cover" }} />
                            <div className="min-w-0">
                              <h6 className="text-xs font-bold text-white truncate leading-tight">{user.name}</h6>
                              <span className="text-[9px] text-[#8b8e9f] truncate block mt-0.5">{user.followers}</span>
                            </div>
                          </div>
                          <button className="px-3 py-1 rounded-lg bg-[#ff7a8a] text-black font-extrabold text-[10px] hover:bg-[#ff9aa6] transition">Follow</button>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </motion.div>
            ) : (
              <>
                <div className="flex gap-2">
                  {(["music", "mood"] as const).map((tab) => (
                    <button
                      key={tab}
                      onClick={() => setActiveTab(tab)}
                      className={`px-3 py-1.5 rounded-full text-sm font-bold transition capitalize ${
                        activeTab === tab ? "bg-[#ff7a8a] text-black" : "bg-[#232323] hover:bg-[#2a2a2a] text-white"
                      }`}
                    >
                      {tab}
                    </button>
                  ))}
                </div>

            <AnimatePresence mode="wait">
              {debouncedSearch.length > 0 ? (
                <motion.div
                  key="search"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                >
                  <h3 className="font-bold text-xl mb-4">
                    Results for &ldquo;{debouncedSearch}&rdquo;
                  </h3>
                  {searchQueryResult.isLoading ? (
                    <div className="grid gap-3">
                      {Array.from({ length: 6 }).map((_, i) => (
                        <div key={i} className="h-16 animate-pulse rounded bg-white/5" />
                      ))}
                    </div>
                  ) : (
                    <div className="grid gap-2">
                      {searchTracks.map((track, i) => (
                        <motion.div
                          key={track.id}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.03 }}
                          onClick={() => play(track, searchTracks)}
                          className="flex items-center gap-3 p-2 rounded-md hover:bg-white/5 cursor-pointer transition group"
                        >
                          <span className="w-5 text-center text-xs text-gray-500 group-hover:hidden">{i + 1}</span>
                          <Play size={14} className="fill-white text-white hidden group-hover:block shrink-0" />
                          <div className="h-12 w-12 shrink-0 rounded overflow-hidden bg-[#282828]">
                            <TrackArt src={track.cover} alt={track.title} size={48} />
                          </div>
                          <div className="min-w-0 flex-1">
                            <h5 className="truncate font-semibold text-sm group-hover:text-[#ff7a8a] transition">{track.title}</h5>
                            <p className="truncate text-xs text-[#b3b3b3]">{track.artist} · {track.album}</p>
                          </div>
                          {track.mood && (
                            <span className="bg-white/10 text-xs text-gray-300 px-2 py-0.5 rounded-full capitalize shrink-0">{track.mood}</span>
                          )}
                        </motion.div>
                      ))}
                    </div>
                  )}
                </motion.div>

              ) : activeMood ? (
                <motion.div
                  key={`mood-${activeMood}`}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                >
                  {(() => {
                    const mood = MOODS.find((m) => m.id === activeMood)!;
                    const Icon = mood.icon;
                    return (
                      <>
                        <div className="flex items-center gap-3 mb-6">
                          <div className="h-12 w-12 rounded-full flex items-center justify-center" style={{ background: mood.color }}>
                            <Icon size={22} className="text-white" />
                          </div>
                          <div>
                            <h3 className="font-bold text-2xl">{mood.label} Mix</h3>
                            <p className="text-sm text-gray-400">Music to match your mood</p>
                          </div>
                          <button
                            onClick={() => setActiveMood(null)}
                            className="ml-auto text-xs text-gray-400 hover:text-white border border-white/20 hover:border-white px-3 py-1 rounded-full transition"
                          >
                            ✕ Close
                          </button>
                        </div>
                        {moodQuery.isLoading ? (
                           <div className="grid gap-3">
                             {Array.from({ length: 8 }).map((_, i) => (
                               <div key={i} className="h-16 animate-pulse rounded bg-white/5" />
                             ))}
                           </div>
                        ) : (
                          <div className="grid gap-2">
                            {moodTracks.map((track, i) => (
                              <motion.div
                                key={track.id}
                                initial={{ opacity: 0, x: -10 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: i * 0.04 }}
                                onClick={() => play(track, moodTracks)}
                                className="flex items-center gap-3 p-2 rounded-md hover:bg-white/5 cursor-pointer transition group"
                              >
                                <span className="w-5 text-center text-xs text-gray-500 group-hover:hidden">{i + 1}</span>
                                <Play size={14} className="fill-white text-white hidden group-hover:block shrink-0" />
                                <div className="h-12 w-12 shrink-0 rounded overflow-hidden bg-[#282828]">
                                  <TrackArt src={track.cover} alt={track.title} size={48} />
                                </div>
                                <div className="min-w-0 flex-1">
                                  <h5 className="truncate font-semibold text-sm group-hover:text-[#ff7a8a] transition">{track.title}</h5>
                                  <p className="truncate text-xs text-[#b3b3b3]">{track.artist}</p>
                                </div>
                              </motion.div>
                            ))}
                          </div>
                        )}
                      </>
                    );
                  })()}
                </motion.div>

              ) : (
                <motion.div
                  key="home"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="flex flex-col gap-7"
                >
                  {/* Hero Banner inside home dashboard with Carousel Animation */}
                  {activeTab === "music" && (
                    <div className="relative h-64 rounded-3xl overflow-hidden border border-white/[0.05] shadow-2xl group bg-[#060813]">
                      <AnimatePresence mode="wait">
                        {HERO_SLIDES.map((slide, index) => {
                          if (index !== currentHeroSlide) return null;
                          return (
                            <motion.div
                              key={slide.id}
                              initial={{ opacity: 0, x: 20 }}
                              animate={{ opacity: 1, x: 0 }}
                              exit={{ opacity: 0, x: -20 }}
                              transition={{ duration: 0.5, ease: "easeInOut" }}
                              className="absolute inset-0 p-8 flex flex-col justify-between bg-cover bg-center"
                              style={{ backgroundImage: `url('${slide.bg}')` }}
                            >
                              <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/40 to-transparent" />
                              
                              <div className="z-10 flex flex-col gap-2 max-w-md">
                                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/10 backdrop-blur-md border border-white/15 text-[10px] font-extrabold uppercase tracking-wider text-[#ff7a8a] w-fit">
                                  {slide.tagline}
                                </div>
                                <h2 className="text-3xl font-black text-white mt-1 leading-tight tracking-tight animate-slideDown">
                                  {slide.title}<span className="text-[#ff7a8a]">{slide.highlightWord}</span>
                                </h2>
                                <p className="text-xs text-white/70 font-medium leading-relaxed mt-1">
                                  {slide.desc}
                                </p>
                              </div>

                              <div className="z-10 flex items-center justify-between w-full">
                                <div className="flex items-center gap-3">
                                  <button
                                    onClick={() => {
                                      const lofi = playlistList.find(p => p.id === slide.playlistId);
                                      if (lofi && lofi.tracks.length > 0) play(lofi.tracks[0], lofi.tracks);
                                    }}
                                    className="h-10 px-6 rounded-xl bg-[#ff7a8a] text-black font-bold text-xs flex items-center gap-2 hover:bg-[#ff9aa6] transition hover:scale-105 active:scale-95 shadow-lg shadow-[#ff7a8a]/20"
                                  >
                                    <Play size={14} className="fill-black text-black ml-0.5" />
                                    Play Mix
                                  </button>
                                  <button
                                    onClick={() => {
                                      const lofi = playlistList.find(p => p.id === slide.playlistId);
                                      if (lofi && lofi.tracks.length > 0) {
                                        const { toggleShuffle } = usePlayerStore.getState();
                                        toggleShuffle();
                                        play(lofi.tracks[Math.floor(Math.random() * lofi.tracks.length)], lofi.tracks);
                                      }
                                    }}
                                    className="h-10 px-6 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white font-bold text-xs flex items-center gap-2 transition hover:scale-105 active:scale-95 backdrop-blur-md"
                                  >
                                    <Shuffle size={14} />
                                    Shuffle
                                  </button>
                                </div>

                                {/* Slider Indicator Dots */}
                                <div className="flex items-center gap-1.5 pb-1">
                                  {HERO_SLIDES.map((_, dotIdx) => (
                                    <button
                                      key={dotIdx}
                                      onClick={() => setCurrentHeroSlide(dotIdx)}
                                      className={`h-1.5 rounded-full transition-all duration-300 ${
                                        dotIdx === currentHeroSlide ? "w-6 bg-[#ff7a8a]" : "w-1.5 bg-white/30 hover:bg-white/50"
                                      }`}
                                    />
                                  ))}
                                </div>
                              </div>
                            </motion.div>
                          );
                        })}
                      </AnimatePresence>
                    </div>
                  )}

                  {/* Trending Hindi Songs */}
                  {activeTab === "music" && (
                    <div className="hidden md:block">
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-black text-lg text-white">Trending Hindi Songs</h3>
                      </div>
                      {trendingQuery.isLoading ? (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {Array.from({ length: 6 }).map((_, i) => (
                            <div key={i} className="h-44 animate-pulse rounded-2xl bg-white/5" />
                          ))}
                        </div>
                      ) : (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {tracks.slice(0, 12).map((track) => {
                            const isCurrent = currentTrack?.id === track.id;
                            return (
                              <div
                                key={track.id}
                                onClick={() => play(track, tracks)}
                                className="p-3 rounded-2xl bg-[#141724]/60 border border-white/[0.04] flex flex-col cursor-pointer group shadow-lg hover:scale-[1.02] hover:bg-[#141724] transition duration-300 relative"
                              >
                                <div className="aspect-square rounded-xl overflow-hidden bg-[#282828] relative mb-3">
                                  <TrackArt src={track.cover} alt={track.title} size={150} className="w-full h-full object-cover" />
                                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition flex items-center justify-center">
                                    <div className="h-10 w-10 rounded-full bg-[#ff7a8a] text-black flex items-center justify-center shadow-lg hover:scale-105 active:scale-95 transition">
                                      {isCurrent && isPlaying ? <Pause size={16} className="fill-black text-black" /> : <Play size={16} className="fill-black text-black ml-0.5" />}
                                    </div>
                                  </div>
                                </div>
                                <h4 className={`font-bold text-xs truncate ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                                  {track.title}
                                </h4>
                                <p className="text-[10px] text-gray-400 truncate mt-0.5">{track.artist}</p>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Global Chill Hits */}
                  {activeTab === "music" && (
                    <div className="hidden md:block">
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-black text-lg text-white">Global Chill Hits</h3>
                      </div>
                      {globalHitsQuery.isLoading ? (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {Array.from({ length: 6 }).map((_, i) => (
                            <div key={i} className="h-44 animate-pulse rounded-2xl bg-white/5" />
                          ))}
                        </div>
                      ) : (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {globalHits.slice(0, 12).map((track) => {
                            const isCurrent = currentTrack?.id === track.id;
                            return (
                              <div
                                key={track.id}
                                onClick={() => play(track, globalHits)}
                                className="p-3 rounded-2xl bg-[#141724]/60 border border-white/[0.04] flex flex-col cursor-pointer group shadow-lg hover:scale-[1.02] hover:bg-[#141724] transition duration-300 relative"
                              >
                                <div className="aspect-square rounded-xl overflow-hidden bg-[#282828] relative mb-3">
                                  <TrackArt src={track.cover} alt={track.title} size={150} className="w-full h-full object-cover" />
                                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition flex items-center justify-center">
                                    <div className="h-10 w-10 rounded-full bg-[#ff7a8a] text-black flex items-center justify-center shadow-lg hover:scale-105 active:scale-95 transition">
                                      {isCurrent && isPlaying ? <Pause size={16} className="fill-black text-black" /> : <Play size={16} className="fill-black text-black ml-0.5" />}
                                    </div>
                                  </div>
                                </div>
                                <h4 className={`font-bold text-xs truncate ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                                  {track.title}
                                </h4>
                                <p className="text-[10px] text-gray-400 truncate mt-0.5">{track.artist}</p>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Trending Songs - Mobile Only */}
                  {activeTab === "music" && (
                    <div className="md:hidden">
                      <div className="flex items-center justify-between mb-3 mt-2">
                        <h3 className="font-black text-lg text-white">Trending on Internet</h3>
                      </div>
                      
                      <div className="flex flex-col gap-2 bg-[#141724]/40 border border-white/[0.03] p-3 rounded-2xl">
                        {tracks.slice(0, 5).map((track, i) => {
                          const isCurrent = currentTrack?.id === track.id;
                          return (
                            <div
                              key={track.id}
                              onClick={() => play(track, tracks)}
                              className={`flex items-center gap-3 p-2 rounded-xl cursor-pointer hover:bg-white/5 active:scale-[0.99] transition duration-200 ${isCurrent ? "bg-white/5" : ""}`}
                            >
                              <div className="w-5 text-center text-xs font-black text-[#ff7a8a]">
                                {i + 1}
                              </div>
                              <div className="relative h-11 w-11 rounded-lg overflow-hidden shrink-0 bg-[#282828] border border-white/5">
                                <TrackArt src={track.cover} alt={track.title} size={44} />
                              </div>
                              <div className="min-w-0 flex-1">
                                <h4 className={`truncate font-extrabold text-xs leading-tight ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                                  {track.title}
                                </h4>
                                <p className="truncate text-[10px] text-white/50 mt-1 font-medium leading-none">{track.artist}</p>
                              </div>
                              <div className="shrink-0 text-white/40 group-hover:text-white transition p-1">
                                {isCurrent && isPlaying ? (
                                  <Pause size={14} className="text-[#ff7a8a]" />
                                ) : (
                                  <Play size={14} />
                                )}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}

                  {/* Playlists Section */}
                  {activeTab === "music" && (
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-black text-lg text-white">Featured LoFi Playlists</h3>
                        <button 
                          onClick={() => { setSelectedPlaylist(null); setAppView("library"); }}
                          className="text-xs font-bold text-[#8b8e9f] hover:text-[#ff7a8a] transition"
                        >
                          View all
                        </button>
                      </div>
                      <div className="flex sm:grid overflow-x-auto sm:overflow-x-visible pb-4 sm:pb-0 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 snap-x scrollbar-none">
                        {playlistList.slice(1, 6).map((playlist) => (
                          <div
                            key={playlist.id}
                            onClick={() => { setSelectedPlaylist(playlist); setAppView("library"); }}
                            className="w-[130px] sm:w-auto shrink-0 snap-start flex flex-col cursor-pointer group"
                          >
                            {/* Playlist Cover Art with Play Button Overlay */}
                            <div className="relative aspect-square w-full rounded-2xl overflow-hidden mb-2 bg-[#1b1c26] border border-white/[0.04] shadow-md">
                              <TrackArt
                                src={playlist.cover}
                                alt={playlist.name}
                                size={150}
                                className="w-full h-full object-cover transition-transform duration-700 ease-out group-hover:scale-105"
                              />
                              <div className="absolute inset-0 bg-black/10 group-hover:bg-black/30 transition-colors" />
                              <div
                                onClick={(e) => {
                                  e.stopPropagation();
                                  if (playlist.tracks.length > 0) {
                                    play(playlist.tracks[0], playlist.tracks);
                                  }
                                }}
                                className="absolute bottom-2.5 right-2.5 h-8 w-8 rounded-full bg-[#ff7a8a] text-black shadow-lg flex items-center justify-center transition hover:bg-[#ff9aa6] hover:scale-105 active:scale-95"
                              >
                                <Play size={12} className="fill-black text-black ml-0.5" />
                              </div>
                            </div>

                            {/* Playlist Metadata Below */}
                            <div className="min-w-0 px-0.5">
                              <h4 className="font-extrabold text-[12px] text-white truncate group-hover:text-[#ff7a8a] transition-colors leading-tight">
                                {playlist.name}
                              </h4>
                              <p className="text-[10px] text-white/50 truncate mt-0.5 font-medium leading-tight">
                                {playlist.desc}
                              </p>
                              <span className="text-[9px] text-[#ff7a8a]/70 font-bold uppercase tracking-wider block mt-1">
                                {playlist.id === "favs" ? likedIds.length : playlist.tracks.length} songs
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Latest Released Music */}
                  {activeTab === "music" && (
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-black text-lg text-white">Latest Released Music</h3>
                      </div>
                      {newReleasesQuery.isLoading ? (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {Array.from({ length: 6 }).map((_, i) => (
                            <div key={i} className="h-44 animate-pulse rounded-2xl bg-white/5" />
                          ))}
                        </div>
                      ) : (
                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                          {newReleases.slice(0, 12).map((track) => {
                            const isCurrent = currentTrack?.id === track.id;
                            return (
                              <div
                                key={track.id}
                                onClick={() => play(track, newReleases)}
                                className="p-3 rounded-2xl bg-[#141724]/60 border border-white/[0.04] flex flex-col cursor-pointer group shadow-lg hover:scale-[1.02] hover:bg-[#141724] transition duration-300 relative"
                              >
                                <div className="aspect-square rounded-xl overflow-hidden bg-[#282828] relative mb-3">
                                  <TrackArt src={track.cover} alt={track.title} size={150} className="w-full h-full object-cover" />
                                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition flex items-center justify-center">
                                    <div className="h-10 w-10 rounded-full bg-[#ff7a8a] text-black flex items-center justify-center shadow-lg hover:scale-105 active:scale-95 transition">
                                      {isCurrent && isPlaying ? <Pause size={16} className="fill-black text-black" /> : <Play size={16} className="fill-black text-black ml-0.5" />}
                                    </div>
                                  </div>
                                </div>
                                <h4 className={`font-bold text-xs truncate ${isCurrent ? "text-[#ff7a8a]" : "text-white"}`}>
                                  {track.title}
                                </h4>
                                <p className="text-[10px] text-gray-400 truncate mt-0.5">{track.artist}</p>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  )}




                </motion.div>
              )}
            </AnimatePresence>
              </>
            )}
          </div>
        </main>
        <div className="hidden sm:block">
          <PlayerShell />
        </div>
      </div>

        {/* ── Right Sidebar (Community Feed / Track Comments) ─────────────────────────────── */}
        <aside className="hidden lg:flex w-[350px] shrink-0 rounded-2xl bg-[#141724] border border-white/[0.04] flex-col overflow-hidden h-[calc(100vh-110px)] p-4 gap-4">
          <div className="flex items-center justify-between border-b border-white/[0.04] pb-3">
            <span className="font-black text-base text-white">Song Community</span>
          </div>

          {currentTrack ? (
            <>
              {/* Active Track Info */}
              <div className="flex items-center gap-3 p-3 rounded-2xl bg-white/[0.02] border border-white/[0.04]">
                <div className="h-12 w-12 rounded-xl overflow-hidden shrink-0 bg-[#282828] border border-white/10 shadow-md">
                  <TrackArt src={currentTrack.cover} alt={currentTrack.title} size={48} />
                </div>
                <div className="min-w-0 flex-1">
                  <h4 className="truncate font-bold text-sm text-white">{currentTrack.title}</h4>
                  <p className="truncate text-xs text-white/50 mt-0.5 font-medium">{currentTrack.artist}</p>
                </div>
              </div>

              {/* Comments Feed Container */}
              <div className="flex-1 overflow-y-auto flex flex-col gap-3.5 pr-0.5">
                {(trackComments[currentTrack.id] || []).map((comment) => (
                  <div key={comment.id} className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04] flex flex-col gap-2">
                    <div className="flex items-center gap-2">
                      <div className="h-6 w-6 rounded-full bg-gradient-to-tr from-[#ff7a8a] to-purple-500 relative overflow-hidden shrink-0 border border-white/10">
                        {comment.avatarUrl ? (
                          <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${comment.avatarUrl})` }} />
                        ) : (
                          <div className="absolute inset-0 bg-[#ff7a8a] text-black text-[9px] font-black flex items-center justify-center">U</div>
                        )}
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-xs font-bold text-white leading-none">{comment.author}</p>
                        <span className="text-[9px] text-[#8b8e9f] mt-0.5 block">{comment.time}</span>
                      </div>
                    </div>
                    <p className="text-[11px] text-white/80 leading-relaxed pl-8">
                      {comment.text}
                    </p>
                  </div>
                ))}
              </div>

              {/* Comment Input Box */}
              <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04] flex flex-col gap-3 mt-auto shrink-0">
                <textarea
                  value={newCommentText}
                  onChange={(e) => setNewCommentText(e.target.value)}
                  className="bg-transparent text-xs w-full outline-none text-white placeholder-[#8b8e9f] resize-none h-12 py-1"
                  placeholder="Share your thoughts on this song..."
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      if (newCommentText.trim()) {
                        const newComment = {
                          id: `c_${Date.now()}`,
                          author: "rishavraj",
                          text: newCommentText.trim(),
                          time: "Just now",
                          avatarUrl: "/covers/late-night-study.png",
                        };
                        setTrackComments((prev) => ({
                          ...prev,
                          [currentTrack.id]: [...(prev[currentTrack.id] || []), newComment],
                        }));
                        setNewCommentText("");
                      }
                    }
                  }}
                />
                <div className="flex items-center justify-between border-t border-white/[0.04] pt-2.5">
                  <div className="flex items-center gap-3 text-[#8b8e9f]">
                    <span className="text-[10px] text-gray-500 font-semibold">Press Enter to post</span>
                  </div>
                  <button
                    onClick={() => {
                      if (newCommentText.trim()) {
                        const newComment = {
                          id: `c_${Date.now()}`,
                          author: "rishavraj",
                          text: newCommentText.trim(),
                          time: "Just now",
                          avatarUrl: "/covers/late-night-study.png",
                        };
                        setTrackComments((prev) => ({
                          ...prev,
                          [currentTrack.id]: [...(prev[currentTrack.id] || []), newComment],
                        }));
                        setNewCommentText("");
                      }
                    }}
                    className="px-4 py-1.5 rounded-xl bg-[#ff7a8a] text-black font-black text-xs hover:bg-[#ff9aa6] transition"
                  >
                    Post
                  </button>
                </div>
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center p-6 gap-3">
              <div className="h-12 w-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-[#8b8e9f]">
                <MusicIcon size={20} />
              </div>
              <p className="font-semibold text-sm text-[#8b8e9f]">No active song</p>
              <p className="text-xs text-gray-500 max-w-[200px]">Play any song to view and join its community discussion.</p>
            </div>
          )}
        </aside>
      </div>

      {/* Mobile Bottom Navigation Bar */}
      <div className="md:hidden fixed bottom-0 left-0 right-0 z-40 bg-[#0c0c0c]/90 backdrop-blur-md border-t border-white/5 px-6 py-2 pb-5 flex justify-around items-center">
        <button
          onClick={() => { setAppView("home"); setSelectedPlaylist(null); }}
          className={`flex flex-col items-center gap-1 transition ${appView === "home" ? "text-[#ff7a8a]" : "text-[#8b8e9f]"}`}
        >
          <Home size={20} className={appView === "home" ? "text-[#ff7a8a] filter drop-shadow-[0_0_8px_rgba(255,122,138,0.5)]" : "text-[#8b8e9f]"} />
          <span className="text-[10px] font-bold">Home</span>
        </button>
        <button
          onClick={() => { setAppView("search"); setSelectedPlaylist(null); }}
          className={`flex flex-col items-center gap-1 transition ${appView === "search" ? "text-[#ff7a8a]" : "text-[#8b8e9f]"}`}
        >
          <Compass size={20} className={appView === "search" ? "text-[#ff7a8a] filter drop-shadow-[0_0_8px_rgba(255,122,138,0.5)]" : "text-[#8b8e9f]"} />
          <span className="text-[10px] font-bold">Explore</span>
        </button>
        <button
          onClick={() => { setAppView("community"); setSelectedPlaylist(null); }}
          className={`flex flex-col items-center gap-1 transition ${appView === "community" ? "text-[#ff7a8a]" : "text-[#8b8e9f]"}`}
        >
          <Users size={20} className={appView === "community" ? "text-[#ff7a8a] filter drop-shadow-[0_0_8px_rgba(255,122,138,0.5)]" : "text-[#8b8e9f]"} />
          <span className="text-[10px] font-bold">Community</span>
        </button>
        <button
          onClick={() => { setAppView("library"); setSelectedPlaylist(null); }}
          className={`flex flex-col items-center gap-1 transition ${appView === "library" ? "text-[#ff7a8a]" : "text-[#8b8e9f]"}`}
        >
          <Library size={20} className={appView === "library" ? "text-[#ff7a8a] filter drop-shadow-[0_0_8px_rgba(255,122,138,0.5)]" : "text-[#8b8e9f]"} />
          <span className="text-[10px] font-bold">Library</span>
        </button>
        <button
          onClick={() => { setAppView("settings"); setSelectedPlaylist(null); }}
          className={`flex flex-col items-center gap-1 transition ${appView === "settings" ? "text-[#ff7a8a]" : "text-[#8b8e9f]"}`}
        >
          <Settings size={20} className={appView === "settings" ? "text-[#ff7a8a] filter drop-shadow-[0_0_8px_rgba(255,122,138,0.5)]" : "text-[#8b8e9f]"} />
          <span className="text-[10px] font-bold">Profile</span>
        </button>
      </div>

      {/* Mobile-only Player Shell at root level to escape stacking context */}
      <div className="sm:hidden">
        <PlayerShell />
      </div>
    </div>
  );
}

function formatDuration(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}
